# FAISS for TEXT - Quick Start
This notebook is a companion of chapter 2 of the "Domain Specific LLMs in Action" book, author Guglielmo Iozzia, [Manning Publications](https://www.manning.com/), 2024.  
The code in this notebook is to introduce readers to the [FAISS](https://faiss.ai/index.html) library. No hardware acceleration required to execute all the code cells.

Install the missing required packages in the Colab VM. Only FAISS for CPU, and [SentenceTransformers](https://www.sbert.net/) not available by default.

In [14]:
# !pip install faiss-cpu sentence-transformers

Import the necessary packages/classes.

In [13]:
""" Module to cluster embeddings and create indices. """
import faiss

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

Set the data corpus for this example and put it into a Pandas DataFrame.

In [15]:
data = [["His secret identity is Peter Parker", "spiderman"],
        ["A businessman and engineer who runs the company Start Industries", "ironman"],
        ["Superhuman spider-powers and abilities after being bitten by a radioactive spider", "spiderman"],
        ["A frail man enhanced to the peak of human physical perfection by an experimental super-soldier serum", "captainamerica"]
        ]

df = pd.DataFrame(data, columns=["text", "context"])

In [16]:
df

                                                text         context
0                His secret identity is Peter Parker       spiderman
1  A businessman and engineer who runs the compan...         ironman
2  Superhuman spider-powers and abilities after b...       spiderman
3  A frail man enhanced to the peak of human phys...  captainamerica

Get embeddings from the data corpus, generate a FAISS index and add the embeddings to it (after normalization).

In [17]:
text = df["text"]
encoder = SentenceTransformer("paraphrase-mpnet-base-v2")
vectors = encoder.encode(text)

In [18]:
vectors

array([[ 0.06908621,  0.40293145, -0.05213062, ...,  0.08801384,
        -0.13445711,  0.06403756],
       [-0.14286482,  0.1006597 , -0.09850159, ..., -0.03079811,
        -0.01277597,  0.01745356],
       [ 0.13080402,  0.07185445,  0.01989626, ...,  0.04210815,
        -0.06912772,  0.05091145],
       [ 0.08117306,  0.14578931,  0.12907588, ..., -0.04734011,
        -0.06134827, -0.04249232]], shape=(4, 768), dtype=float32)

In [19]:
vector_dimension = vectors.shape[1]
print("Vector Dimension:", vector_dimension)
l2_index = faiss.IndexFlatL2(vector_dimension)
print("L2 Index:", l2_index)
faiss.normalize_L2(vectors)
l2_index.add(vectors)

Vector Dimension: 768
L2 Index: <faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x157fad620> >

In [20]:
vectors[0]

array([ 1.98383462e-02,  1.15703173e-01, -1.49694895e-02,  2.47340444e-02,
        3.79682481e-02, -2.29993910e-02,  6.02637827e-02, -9.17371176e-03,
        1.37601495e-02,  2.50961538e-02, -3.89766172e-02, -2.03392878e-02,
        1.12486612e-02, -3.52051333e-02,  1.80403553e-02, -2.77950726e-02,
        2.56065838e-02, -3.27652283e-02,  3.67175648e-03,  3.50672901e-02,
       -1.94805637e-02,  1.34802051e-02,  7.72050442e-03,  6.37777373e-02,
        4.42951657e-02, -2.71252804e-02,  4.21068594e-02, -4.94873151e-03,
        1.64286382e-02,  2.45893188e-02, -2.36443314e-03, -1.27049424e-02,
       -1.43039636e-02,  3.26322950e-02,  9.29414574e-03,  2.90941782e-02,
        5.52186146e-02,  9.94965341e-03,  4.70733084e-03, -1.79625656e-02,
       -5.42631000e-02,  2.99972612e-02,  2.70248782e-02, -1.41599146e-03,
       -1.08192768e-02, -3.85977030e-02,  4.21064571e-02,  5.43395244e-02,
       -5.73823377e-02,  2.10921522e-02,  2.65319627e-02,  1.32841067e-02,
        3.84260677e-02, -3.35763358e-02,  8.32376480e-02, -1.26125723e-01,
       -1.37598533e-02, -5.80018237e-02, -3.11107896e-02, -2.40016375e-02,
        4.04212475e-02, -3.08035985e-02, -2.29332242e-02, -5.99476742e-03,
        6.65133493e-03, -6.54906547e-03,  9.85696688e-02,  2.96205422e-03,
        5.27574867e-03, -1.99818816e-02, -1.39304213e-02,  1.56174274e-02,
       -1.01078104e-03,  4.53537144e-02,  6.62639271e-03,  5.28512113e-02,
        4.55094725e-02, -7.72345485e-03,  5.43722417e-04, -6.97237998e-03,
       -2.64647286e-02, -9.20332875e-03, -9.41101648e-03,  2.34851632e-02,
       -2.64158510e-02,  7.56002665e-02,  7.92459585e-03,  3.63073200e-02,
       -6.35400862e-02, -2.58041732e-02,  4.85409126e-02, -2.52371188e-02,
        5.33547439e-02, -1.22654866e-02,  6.20133244e-02,  1.73573978e-02,
       -1.87295862e-02,  1.24843847e-02, -1.30995475e-02,  4.90784682e-02,
       -4.40466069e-02, -3.33751664e-02,  1.02642858e-02,  4.44573313e-02,
        3.02111059e-02,  3.25976610e-02,  6.02780515e-03, -5.17776702e-03,
        2.65571270e-02, -1.47683844e-02,  4.69714962e-02, -4.10064496e-02,
       -2.53478847e-02,  4.13813516e-02,  9.76519194e-03, -6.36072382e-02,
        1.55462511e-03,  2.34388970e-02,  1.19996537e-02, -9.69778281e-03,
        2.05718558e-02, -7.42674572e-03, -5.75076528e-02, -9.71458293e-03,
        2.42252201e-02, -1.62469968e-02, -2.60911975e-02, -1.18612181e-02,
       -8.32369179e-03,  4.35344540e-02, -2.13907883e-02, -6.33813441e-02,
        4.72850055e-02, -1.87532883e-02, -5.32264961e-03,  1.25517072e-02,
       -3.05863866e-03, -1.17532872e-02,  2.11264156e-02,  1.10067474e-02,
       -1.54854748e-02,  1.15660457e-02, -4.56643291e-02,  3.21697518e-02,
        3.99293713e-02, -5.50348237e-02,  1.42005859e-02, -5.87670766e-02,
       -3.23633454e-03,  3.75872217e-02,  3.30549665e-02,  3.20758149e-02,
        2.85863709e-02, -2.36067008e-02,  5.84050361e-03,  2.19452735e-02,
        2.76229251e-03, -4.89622764e-02, -2.53940076e-02, -3.54193524e-02,
       -4.42029064e-04, -3.62379178e-02,  5.21800295e-02,  1.25724664e-02,
       -3.52979787e-02, -9.06075537e-02,  1.10347912e-01, -1.39415544e-02,
        9.36316624e-02, -3.38874906e-02, -3.13818827e-02, -2.65071746e-02,
       -1.00729810e-02, -1.36272404e-02,  1.23559963e-02,  1.47321494e-02,
       -1.51015604e-02, -5.39934859e-02, -2.30846219e-02,  1.94878299e-02,
        2.39204150e-02,  3.09171784e-03, -8.55086744e-03,  3.70189771e-02,
       -6.11372069e-02,  2.77712420e-02, -6.17784299e-02, -4.11419384e-02,
        2.03904454e-02,  2.81975046e-02,  4.97915186e-02, -1.71357896e-02,
        2.36439500e-02, -3.80189344e-02,  1.24853645e-02,  8.15361924e-03,
        7.20329164e-03,  4.71325628e-02, -1.48991579e-02,  3.18014137e-02,
        7.51276687e-03, -4.76068864e-03, -1.43999495e-02,  7.54703134e-02,
       -1.69230010e-02,  2.00819504e-02,  5.09378240e-02, -3.52312028e-02,
       -1.09388242e-02, -1.62787810e-02, -3.67617235e-02, -8.70722998e-03,
        1.77198276e-02, -1.17022414e-02,  1.53148975e-02, -2.90074814e-02,
        2.60718036e-02,  7.05363741e-03,  2.15026680e-02, -3.81852537e-02,
       -7.36755494e-04, -3.89939621e-02,  5.37808537e-02, -3.66356893e-04,
       -1.03692636e-01, -4.15813252e-02,  2.46987492e-02,  1.35190031e-02,
        2.46325624e-03,  2.70461459e-02,  2.56771762e-02,  4.86748759e-03,
        5.17133158e-03,  1.21998116e-02,  2.06735395e-02, -1.20910583e-02,
        4.25795615e-02,  6.94392156e-03,  4.03794907e-02, -1.26242250e-01,
        4.05620262e-02,  7.02842772e-02,  3.16814668e-02, -3.87811176e-02,
       -1.36593608e-02, -5.89484908e-03,  2.36222800e-02,  3.18657160e-02,
        1.99168567e-02, -1.06996866e-02, -3.16595472e-02,  5.60716446e-03,
        1.03897993e-02,  5.50126247e-02, -2.03300064e-04, -4.18244265e-02,
       -2.97443965e-03,  1.13383513e-02,  7.30967373e-02,  4.10290398e-02,
       -5.08426204e-02,  1.79189313e-02, -2.01585926e-02, -5.11757471e-02,
       -1.46120796e-02,  4.02068123e-02, -1.33111458e-02,  5.32260444e-03,
       -1.91045515e-02,  1.60467364e-02, -2.42789574e-02, -5.94452606e-04,
       -3.21909450e-02, -1.91567056e-02,  1.46280676e-02,  9.29535460e-03,
       -9.55741331e-02, -3.28537561e-02,  5.62369497e-03, -1.51503412e-02,
        2.76896879e-02,  6.89791143e-03, -1.20092928e-03,  1.17068198e-02,
        5.04089892e-03, -1.75072663e-02,  4.77272272e-03, -3.38955619e-03,
        3.57412659e-02, -5.40403686e-02, -2.92798746e-02,  2.46044993e-02,
        4.82768053e-03,  3.23024988e-02,  2.83956006e-02, -3.15596396e-03,
       -5.42251915e-02, -9.64124128e-02, -5.00385314e-02, -8.86638016e-02,
        1.89850535e-02,  5.00837900e-03, -4.71975328e-03,  5.90801938e-03,
        1.13622556e-02, -3.84333320e-02,  3.43018211e-02,  3.14971022e-02,
       -3.67136747e-02, -1.89791154e-02, -3.39552574e-02,  3.67990956e-02,
       -1.54740931e-02, -2.44649984e-02,  6.63491040e-02, -3.20886001e-02,
        2.34966092e-02, -2.27159280e-02,  8.15126579e-03, -5.03376238e-02,
       -3.01567819e-02,  2.29349267e-02,  1.78519264e-02, -4.12975065e-02,
        1.83158945e-02, -3.31510487e-03,  3.42751332e-02,  3.07841953e-02,
        4.78768013e-02,  6.25223890e-02, -2.39610597e-02,  3.24358121e-02,
       -2.37911567e-02,  2.51624696e-02,  7.12782890e-03, -1.36906421e-02,
       -2.40846239e-02,  1.47967851e-02, -3.30074318e-02, -2.20801011e-02,
        3.40986140e-02,  1.98283400e-02, -6.02647066e-02,  3.60783539e-03,
       -6.14336915e-02,  3.79117429e-02, -5.88299185e-02, -4.37232479e-02,
        2.35702600e-02, -1.96727253e-02,  4.20989506e-02,  4.29584570e-02,
        3.17221172e-02, -2.47155484e-02, -8.28061812e-03, -3.16754170e-02,
       -1.85652263e-02, -2.05478612e-02,  4.06224877e-02,  4.91515659e-02,
       -5.65001145e-02, -7.23333582e-02, -5.15806722e-03,  3.64181623e-02,
        5.90819791e-02, -3.89184840e-02, -8.19152966e-03,  3.77250486e-03,
        1.13827959e-02,  7.32359663e-02,  2.94204094e-02, -3.30851786e-02,
        3.49646877e-03,  3.07245050e-02,  2.81496085e-02,  1.31363943e-02,
        8.59348010e-03, -1.33680052e-03, -5.93200661e-02, -1.44194672e-02,
       -1.49501543e-02,  7.22682889e-05, -7.80729018e-03, -3.38928625e-02,
       -8.32825527e-03, -9.43035726e-03, -7.05246406e-04, -4.50328030e-02,
       -4.54771854e-02,  1.80060267e-02,  3.77400890e-02, -4.52804342e-02,
       -3.25077702e-03, -9.40560102e-02,  7.15560326e-03, -1.14337821e-02,
       -2.99221147e-02,  1.78765357e-02,  6.32580835e-03, -6.85506966e-03,
       -1.92851070e-02,  4.17416878e-02,  6.45231921e-04,  3.30861285e-02,
        1.60696660e-03, -5.52919097e-02,  2.80092582e-02, -2.04874072e-02,
       -5.43136634e-02, -6.35265633e-02, -5.72974011e-02,  3.71660516e-02,
       -2.61231475e-02, -1.60257779e-02, -3.99791403e-03, -9.00321603e-02,
       -2.56033726e-02, -2.39986684e-02,  4.96966057e-02, -5.24041280e-02,
        2.32960260e-03, -2.29221713e-02,  2.55880821e-02,  2.55089607e-02,
        1.17180147e-03, -9.97793302e-03, -1.27647575e-02, -6.44450169e-03,
        1.35247624e-02, -4.69593517e-03,  4.62064445e-02, -5.34977354e-02,
        1.10953962e-02,  8.46249089e-02, -3.87116335e-02,  7.39973597e-03,
        2.49256957e-02,  7.35386014e-02,  1.59279872e-02, -2.12005805e-02,
        2.58070137e-02,  5.25177754e-02, -1.57507975e-02, -9.00442898e-03,
       -1.15134278e-02, -7.72182941e-02, -2.11744511e-04,  2.04054136e-02,
       -1.84433833e-02,  3.10614635e-03, -9.91104636e-03,  8.68818164e-02,
       -3.58545259e-02,  7.28567094e-02, -1.17839389e-02, -8.25633947e-03,
        5.58543317e-02, -1.65948477e-02, -1.05201211e-02,  2.70278268e-02,
        5.87390910e-04,  1.05206616e-01,  4.71343100e-02,  1.13650477e-02,
       -6.57357872e-02,  3.85365598e-02,  2.38081496e-02,  1.11260097e-02,
       -1.91552583e-02, -3.75227667e-02,  3.58275287e-02, -1.50032239e-02,
       -1.89759899e-02, -2.34364998e-02, -2.49361563e-02, -7.50938132e-02,
       -3.31080495e-03, -1.12531401e-01,  3.03381104e-02,  1.31934602e-03,
       -3.36091444e-02,  3.60754915e-02, -5.44898037e-04,  8.48227292e-02,
        3.38732377e-02,  1.06452242e-03, -4.01906716e-03,  1.24185458e-02,
       -2.12701764e-02, -1.01404143e-02,  2.51218341e-02,  1.42396661e-03,
       -8.28276947e-03,  5.56636648e-03,  2.31745793e-03,  4.64199446e-02,
       -4.94654104e-02, -4.18974832e-02,  4.29799221e-02, -3.38144712e-02,
       -2.42936052e-02, -2.16244869e-02,  2.22257785e-02,  3.25616598e-02,
       -6.69807270e-02, -5.37684653e-03,  2.80817449e-02, -7.94754103e-02,
        5.45383431e-04,  1.87598951e-02, -1.68634078e-03, -4.89714742e-03,
       -3.51217426e-02, -4.50152941e-02, -3.80280279e-02,  4.40155528e-02,
        2.36907229e-02,  1.13121923e-02, -1.00204907e-02, -4.80400547e-02,
       -5.45773245e-02, -2.90142484e-02,  3.88523098e-04,  1.07198087e-02,
       -1.44375218e-02,  4.17491328e-03,  7.20869517e-03, -3.44895087e-02,
        8.02140031e-03,  2.28321571e-02, -2.39997432e-02, -3.87810101e-03,
       -5.47616743e-02,  4.34838757e-02,  1.22170309e-02,  1.17389439e-02,
       -7.44335800e-02,  1.36908278e-01, -1.55280521e-02,  2.02226564e-02,
       -7.71887554e-03,  3.74383689e-03,  2.64104269e-02, -1.46677215e-02,
        2.31201784e-03, -1.10448925e-02, -1.71667840e-02,  4.07609791e-02,
       -1.04165487e-02, -5.24298176e-02,  2.26915665e-02, -1.86924171e-02,
        4.80554998e-02, -2.93247681e-03,  4.54793051e-02, -1.70012321e-02,
        3.08006704e-02, -1.80719979e-02, -2.86562704e-02,  2.01422479e-02,
        2.21071225e-02,  1.07766297e-02,  4.93173648e-05,  2.65027932e-03,
        6.27565011e-03, -3.19180787e-02, -9.90431663e-03, -2.92111840e-02,
        3.74309756e-02,  1.89343430e-02, -4.96314466e-02,  2.21749954e-02,
        3.20815071e-02,  5.52153506e-04,  4.50203195e-03,  1.32400235e-02,
        3.91621292e-02, -2.58932188e-02, -4.27313410e-02,  1.69697739e-02,
       -3.29169407e-02, -4.03439701e-02,  8.75930861e-03,  1.56371128e-02,
        2.32793186e-02, -1.88699346e-02, -2.44597830e-02, -6.73935786e-02,
        3.03362366e-02,  4.78436612e-02,  4.15585795e-03, -3.35867022e-04,
        2.72445194e-02,  4.63233776e-02,  3.63010424e-03, -4.66319509e-02,
        3.01935915e-02, -3.92227396e-02,  3.60772130e-03, -3.09518795e-03,
        3.03763598e-02, -2.59243399e-02,  6.56473357e-03,  1.85426492e-02,
        1.15077151e-02, -3.32920589e-02,  4.03972715e-02,  2.04790886e-02,
        2.73541510e-02,  3.09788529e-02, -1.15015144e-02,  2.62090866e-03,
       -6.90472545e-03,  2.02665720e-02, -5.57765998e-02, -1.14181340e-02,
        1.48765063e-02, -4.99149319e-03,  9.19895153e-03,  7.66497180e-02,
       -3.87707241e-02, -1.51968868e-02,  1.81649700e-01,  1.93610359e-02,
       -1.50200436e-02,  4.75336611e-02,  3.31741907e-02, -1.10398494e-02,
        1.12616681e-01, -3.07142697e-02, -9.22070369e-02,  1.99642722e-02,
        4.47617238e-03, -1.86768565e-02,  4.41165119e-02, -9.09568220e-02,
        6.31593913e-02,  5.33229904e-04, -3.29074338e-02, -6.14922540e-03,
       -1.71369445e-02,  1.18240400e-03, -1.54187414e-03,  2.01198515e-02,
       -2.25590691e-02, -3.41897532e-02, -7.62446970e-02, -1.70259885e-02,
        2.56902142e-03, -6.37945952e-03, -6.64809942e-02, -8.82846396e-03,
       -2.10561771e-02,  1.04426490e-02, -1.34871723e-02,  5.80643155e-02,
       -2.54924037e-02, -2.02262513e-02,  1.38063524e-02,  2.23747827e-02,
        2.21650470e-02, -6.75677136e-03, -9.30016302e-03, -4.19086181e-02,
       -3.70349810e-02, -3.84357013e-02, -2.87068821e-02,  5.20495465e-03,
        1.11965714e-02, -4.97885235e-03,  1.39744021e-02, -1.98828382e-03,
       -2.36937162e-02,  2.47316156e-02, -1.70545299e-02, -6.90571871e-03,
        4.64837700e-02,  9.22918990e-02, -1.83673408e-02, -4.94318316e-03,
       -3.15898610e-03,  3.94274760e-03, -3.13898697e-02,  4.08323742e-02,
        6.97164759e-02,  2.43745018e-02,  2.60152295e-02, -1.10905217e-02,
        2.43252772e-03,  2.17230767e-02, -3.78634818e-02,  1.19985333e-02,
        1.25369010e-03, -4.89304401e-03, -1.24474838e-02,  3.60049419e-02,
       -1.41678136e-02, -1.12199103e-02, -6.25735372e-02, -2.31421506e-03,
       -5.57703199e-03,  1.65863689e-02,  1.62168480e-02,  1.82788223e-02,
        4.63507771e-02,  6.40989468e-02, -3.77934799e-03,  2.63947342e-03,
        2.33205054e-02,  1.47728138e-02,  8.59676767e-03,  2.49343421e-02,
        1.78725254e-02,  3.20143066e-02, -3.89770009e-02,  2.89082807e-02,
        5.47659323e-02, -2.35475483e-03,  2.53810827e-02, -2.27833781e-02,
        5.64373061e-02, -2.00972892e-02,  2.27496158e-02, -1.35310087e-02,
        6.09791577e-02, -1.36431446e-02, -5.43931052e-02, -6.30882457e-02,
       -1.29449842e-02, -5.53481504e-02, -1.51348347e-02, -2.28333306e-02,
        1.42855179e-02,  4.12044451e-02,  3.63959670e-02, -1.65499630e-03,
        9.08058956e-02,  3.28248516e-02, -2.73126420e-02, -1.23224249e-02,
        5.84081188e-03,  3.03855427e-02,  6.16359115e-02, -2.32014339e-02,
       -3.78733277e-02, -1.74561385e-02, -7.64227509e-02,  2.85830032e-02,
       -5.57645923e-03, -2.82590296e-02,  2.32737828e-02, -2.68688314e-02,
       -6.91812709e-02,  8.99950974e-04,  8.72927811e-03,  6.28926829e-02,
       -3.71969379e-02, -5.92402183e-02,  4.74056974e-02, -4.12143394e-02,
        7.91577250e-03, -5.29841986e-03,  1.60897672e-02,  2.71461941e-02,
        3.89363170e-02,  2.52734795e-02, -3.86098288e-02,  1.83886085e-02],
      dtype=float32)

Prepare a search text to be used for similarity search with FAISS on the generated index.

In [21]:
search_text = "He throws webs"
search_vector = encoder.encode(search_text)
search_vector_as_array = np.array([search_vector])
faiss.normalize_L2(search_vector_as_array)

Perform a search within the created index (calculation of the distances between the search text and the strings within the index).

In [22]:
k = l2_index.ntotal
distances, ann = l2_index.search(search_vector_as_array, k=k)

In [23]:
distances

array([[1.5010695, 1.552392 , 1.642769 , 1.731641 ]], dtype=float32)

In [24]:
ann

array([[2, 0, 1, 3]])

Prepare the results to be displayed in a user-friendly format.

In [25]:
search_results = pd.DataFrame({"distances": distances[0], "ann": ann[0]})
merged_df = pd.merge(search_results, df, left_on="ann", right_index=True)
merged_df.head()

,distances,ann,text,context
0,1.501070,2,Superhuman spider-powers and abilities after b...,spiderman
1,1.552392,0,His secret identity is Peter Parker,spiderman
2,1.642769,1,A businessman and engineer who runs the compan...,ironman
3,1.731641,3,A frail man enhanced to the peak of human phys...,captainamerica